# docker-compose.yml
#
# Define serviços Docker para monitoramento e relatório de e-mails SMTP.
# Inclui smtp-relay (Exim), smtp-relay-db (MySQL) e app (Flask).
# Comentários resumem opções das variáveis.

services:
  smtp-relay:
    image: aprendendolinux/exim-relay:latest
    restart: always
    container_name: smtp-relay
    hostname: smtp-relay
    environment:
      # SMTP_SERVER: Hostname do servidor SMTP (ex.: smtp-relay.gmail.com, email-smtp.us-west-2.amazonaws.com).
      - SMTP_SERVER=smtp-relay.example.com
      # SMTP_PORT: Porta SMTP (25 não seguro, 587 STARTTLS, 465 SSL).
      - SMTP_PORT=587
      # SMTP_USERNAME: Usuário SMTP (ex.: user@example.com, api_key).
      - SMTP_USERNAME=user@example.com
      # SMTP_PASSWORD: Senha SMTP (ex.: xxxxxxxxxxxxxxxx).
      - SMTP_PASSWORD=xxxxxxxxxxxxxxxx
      # SERVER_HOSTNAME: FQDN do Exim (ex.: mail.example.com).
      - SERVER_HOSTNAME=mail.example.com
      # RELAY_NETS: Redes permitidas (ex.: 0.0.0.0/0, 192.168.1.0/24).
      - RELAY_NETS=0.0.0.0/0
      # TZ: Fuso horário (ex.: America/Sao_Paulo, UTC).
      - TZ=America/Sao_Paulo
      # DECODE_SUBJECT: Decodifica assuntos MIME (yes, no).
      - DECODE_SUBJECT=yes
    volumes:
      - /srv/smtp-relay/logs:/var/log/exim4
    ports:
      - 25:25
      - 2525:25

  smtp-relay-db:
    image: mysql:latest
    restart: always
    container_name: smtp-relay-db
    hostname: smtp-relay-db
    environment:
      # MYSQL_ROOT_PASSWORD: Senha root (ex.: senha_complexa).
      MYSQL_ROOT_PASSWORD: 'xxxxxxxxxxxxxxxx'
      # MYSQL_DATABASE: Nome do banco (ex.: smtp_cpd).
      MYSQL_DATABASE: smtp_cpd
      # MYSQL_USER: Usuário MySQL (ex.: smtp_user).
      MYSQL_USER: smtp_user
      # MYSQL_PASSWORD: Senha do usuário (ex.: senha_complexa).
      MYSQL_PASSWORD: 'xxxxxxxxxxxxxxxx'
    volumes:
      - /srv/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  smtp-relay:
    image: clubenaval/relatorios-smtp:latest
    restart: always
    container_name: app
    hostname: app
    environment:
      # DB_HOST: Host do banco (ex.: smtp-relay-db, 192.168.1.100).
      - DB_HOST=smtp-relay-db
      # DB_USER: Usuário MySQL (ex.: smtp_user, root).
      - DB_USER=smtp_user
      # DB_PASSWORD: Senha do usuário (ex.: senha_complexa).
      - DB_PASSWORD='xxxxxxxxxxxxxxxx'
      # DB_NAME: Nome do banco (ex.: smtp_cpd).
      - DB_NAME=smtp_cpd
      # LOG_DIR: Diretório de logs (ex.: /app/logs).
      - LOG_DIR=/app/logs
      # TZ: Fuso horário (ex.: America/Sao_Paulo).
      - TZ=America/Sao_Paulo
      # AUTH_MODE: Modo de autenticação (AD, DB). Se DB, obrigatório configurar servidor SMTP para recuperação de senha.
      - AUTH_MODE=DB
      # LDAP_HOST: Servidor LDAP (ex.: 192.168.1.100). Usado se AUTH_MODE=AD.
      # - LDAP_HOST=192.168.1.100
      # LDAP_DOMAIN: Domínio AD (ex.: @example.com). Usado se AUTH_MODE=AD.
      # - LDAP_DOMAIN=@example.com
      # LDAP_BASE_DN: Base DN (ex.: DC=example,DC=com). Usado se AUTH_MODE=AD.
      # - LDAP_BASE_DN=DC=example,DC=com
      # LDAP_GROUP_DN: Grupo DN (ex.: CN=Users,DC=example,DC=com). Usado se AUTH_MODE=AD.
      # - LDAP_GROUP_DN=CN=Users,DC=example,DC=com
      # SCHEDULE_TYPE: Agendamento (minutes, time).
      - SCHEDULE_TYPE=minutes
      # SCHEDULE_INTERVAL_MINUTES: Intervalo em minutos (ex.: 2). Usado se SCHEDULE_TYPE=minutes.
      - SCHEDULE_INTERVAL_MINUTES=2
      # SCHEDULE_TIME: Horário fixo (ex.: 16:40). Usado se SCHEDULE_TYPE=time.
      # - SCHEDULE_TIME=16:40
      # DB_PORT: Porta MySQL (ex.: 3306, 3307). Padrão: 3306.
      # - DB_PORT=3306
      # SMTP_SERVER: Servidor SMTP para recuperação de senha (ex.: smtp-relay, smtp-relay.gmail.com). Usado se AUTH_MODE=DB.
      - SMTP_SERVER=smtp-relay
      # SMTP_PORT: Porta SMTP (25 não seguro, 587 STARTTLS, 465 SSL). Usado se AUTH_MODE=DB.
      - SMTP_PORT=25
      # SMTP_USERNAME: Usuário SMTP (ex.: user@example.com). Usado se AUTH_MODE=DB e SMTP_AUTHENTICATED=True.
      # - SMTP_USERNAME=user@example.com
      # SMTP_PASSWORD: Senha SMTP (ex.: xxxxxxxxxxxxxxxx). Usado se AUTH_MODE=DB e SMTP_AUTHENTICATED=True.
      # - SMTP_PASSWORD=xxxxxxxxxxxxxxxx
      # SMTP_FROM: E-mail remetente (ex.: noreply@example.com). Usado se AUTH_MODE=DB.
      - SMTP_FROM=noreply@example.com
      # SMTP_FROM_NAME: Nome remetente (ex.: Sistema de Relatórios). Usado se AUTH_MODE=DB.
      - SMTP_FROM_NAME='Sistema de Relatórios'
      # SMTP_USE_TLS: Ativa TLS (True, False). Usado se AUTH_MODE=DB e SMTP_AUTHENTICATED=True.
      # - SMTP_USE_TLS=True
      # SMTP_USE_SSL: Ativa SSL (True, False). Usado se AUTH_MODE=DB e SMTP_AUTHENTICATED=True.
      # - SMTP_USE_SSL=False
      # SMTP_AUTHENTICATED: Requer autenticação SMTP (True, False). Usado se AUTH_MODE=DB.
      - SMTP_AUTHENTICATED=False
    volumes:
      - /srv/smtp-relay/logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - smtp-relay-db
      - smtp-relay

networks:
  default:
    driver: bridge
    name: smtp-network
